### PR TITLE
updated --cp behavior

### PR DESCRIPTION
**Pull request by SamMarkowitz**
Signed-off-by: Sam Markowitz <sam.markowitz@hp.com>

### CODE REVIEW

**Comment by orius123** [comment]
we should mention that if the user defines --cp it overrides the default and the base content will not be available.

**Comment by meirwah** [comment]
unless he points -cp to base content...

**Comment by SamMarkowitz** [comment]
Oh. Did not know that. I will put something in.

**Comment by SamMarkowitz** [comment]
Added comment about the default being overridden.

**Pull request merged**
