### PR TITLE
Get started linux

### LINKED ISSUE #147: Download CLI from website for linux users?
I think we have an issue in our download page...
It's unfriendly for the Linux user, since he cannot see the download link , so he cannot copy paste it...
I think we should give instructions suitable for Linux users (like to last version..)

### PR DESCRIPTION
**Pull request by SamMarkowitz**
fixes #147

### CODE REVIEW

**Comment by SamMarkowitz** [comment]
I don't like the way it looks. The first step is too crowded and it's a bit awkward.

image

How about going back to 4 steps:

1. Download - Windows, Linux
2. Start the CLI - Go to cslang/bin or Docker stuff
3. Current step 2
4. Current step 3

And maybe add small logos instead of words "Windows" and "Linux"?

Thoughts, comments, suggestions @oritstone @gal1419 @gfachler?

**Comment by gal1419** [comment]
What have you decided? 
Do you want to keep it that way or changed it back to 4 steps? 
@meshipeer @SamMarkowitz  @gfachler 

@SamMarkowitz, this branch has conflicts, could you make sure that you work on the latest version of master and then push again? Please note that I pushed a new version with the double download button.

**Comment by oritstone** [comment]
We need to decide if we want to address it - add the linux command specifically, in addition to the specific Download for Linux button

**Comment by gal1419** [comment]
@oritstone I think we can close this pull request if we have decided to stay with the current getting started page for now, right?

**Pull request closed without merging**
