### PR TITLE
Consolidate get started

### LINKED ISSUE #139: getstarted section
unzip cmd is mentioned twice:

image

we can remove the one is step 2.

### PR DESCRIPTION
**Pull request by SamMarkowitz**
fixes #139 

temporary link: https://mighty-citadel-3431.herokuapp.com/#/getstarted#top

It's still a little strange because step 1 is really 2 steps, but I think it's the best option

### CODE REVIEW

**Comment by meirwah** [comment]
@SamMarkowitz ping me to review the site..

**Comment by meirwah** [comment]
:+1:

**Comment by gal1419** [comment]
it looks ok, but I find it really confusing, having the word "Run" in step 1 and step 2. 
If you ask me, it is more confusing than the old version.

**Comment by SamMarkowitz** [comment]
One is running the CLI and the other is running the flow. We can change one to "execute" instead, or maybe "start the CLI", "open the CLI". Any other suggestions @gal1419, @meirwah, @oritstone?

**Comment by meirwah** [comment]
I prefer "start the CLI"

**Comment by gal1419** [comment]
I vote "Start the CLI"

**Comment by SamMarkowitz** [comment]
Okay. Reworded the first step. @gal1419 @meirwah @oritstone does this do the trick.

Temp link: https://warm-sierra-6013.herokuapp.com/#/getstarted#top

**Comment by gal1419** [comment]
better, maybe @gfachler has something to say

**Comment by meirwah** [comment]
:+1:

**Pull request merged**
