### PR TITLE
updated to new video

### PR DESCRIPTION
**Pull request by SamMarkowitz**
Signed-off-by: SamMarkowitz <sam.markowitz@hpe.com>

### CODE REVIEW

**Comment by gal1419** [comment]
@SamMarkowitz can you please check why the Travis build failed?

**Comment by SamMarkowitz** [comment]
@gal1419 will need your help on this one. It's a bit beyond my purview. I have no idea why it's failing. I can't imagine it's in anyway related to my change.

**Comment by Bonczidai** [comment]
the build also fails on master - not related to this specific branch

seems to me that we have a dependency conflict for angular, @gal1419 can you please look into this issue?

**Comment by gal1419** [comment]
sure, but it will take some time.. only next week.

**Comment by Bonczidai** [comment]
@gal1419 did you have a chance to look into this issue?

**Comment by gal1419** [comment]
working on it

**Comment by gal1419** [comment]
Sam, you can continue - you will need to take the latest changes from master and then commit again with your changes

**Comment by SamMarkowitz** [comment]
@gal1419 I merged in master. You can go ahead and merge this PR.

**Pull request merged**
