### PR TITLE
Get started prereq

### LINKED ISSUE #140: get started missing Java pre-requisite
need to add to the get started page , our Java  pre-requisite .

### PR DESCRIPTION
**Pull request by SamMarkowitz**
fixes #140

### CODE REVIEW

**Comment by meirwah** [comment]
@gal1419 can you verify it looks good in the website?

**Comment by SamMarkowitz** [comment]
image

**Comment by meirwah** [comment]
:+1:

**Comment by gal1419** [comment]
it looks ok, but do we want to put it here? in the description i mean..

**Pull request merged**
