### PR TITLE
getting started page updates - added linux download button.

### LINKED ISSUE #147: Download CLI from website for linux users?
I think we have an issue in our download page...
It's unfriendly for the Linux user, since he cannot see the download link , so he cannot copy paste it...
I think we should give instructions suitable for Linux users (like to last version..)

### PR DESCRIPTION
**Pull request by gal1419**
fixes #147

get linux

### CODE REVIEW

**Comment by gal1419** [comment]
If you don't have remarks we are ready for merge

**Comment by oritstone** [comment]
@meirwah @orius123 
We decided to go with a split button for downloading from windows or from linux:

Do you think it is enough or is it important to have the linux command written somewhere as well?
I think the page is much more elegant without it...

**Comment by orius123** [comment]
Can you share a pic?
I like commands but that is personal..

**Comment by SamMarkowitz** [comment]
linux

**Comment by meirwah** [comment]
I'm for CMD

**Pull request merged**
