### PR TITLE
Openshift image

### LINKED ISSUE #148: Add images for OpenShift on workwith folder
Hello, It would be great to add images for new content recently added like OpenShift, Stackato, AWS, Google Cloud Platform, Chef, HP Public Cloud in workwith folder

Thanks

### PR DESCRIPTION
**Pull request by SamMarkowitz**
fixes #148 

Temp link for review: https://quiet-mountain-9586.herokuapp.com/#/

### CODE REVIEW

**Comment by gal1419** [comment]
looks good

**Comment by mbettan** [comment]
@SamMarkowitz - Images Bar with OpenStack Jenkins Docker... is not moving anymore with chrome

**Comment by gal1419** [comment]
works just fine here.. try to refresh

**Comment by SamMarkowitz** [comment]
Works for me on Chrome as well.

**Comment by mbettan** [comment]
It's weird, probably my laptop, both IE and chrome is not working

**Pull request merged**
