### PR TITLE
New Name

### PR DESCRIPTION
**Pull request by orius123**

### CODE REVIEW

**Comment by orius123** [comment]
@gfachler @meshipeer @meirwah @oritstone @arjuan
Started working on the new site.
Available at http://cloudslang.io
feedback is welcome :fireworks:

**Comment by meshipeer** [comment]
first, looks good :)
1. the blogs not working
2. please remove Avi's picture. @SamMarkowitz do you want to us to add yours?
3. the getting started-> write section, the 'write' is weird... but i don't have another suggestion...

**Comment by orius123** [comment]
Will enable blog tomorrow.
Planned to check Asi's pictures
The word `write` or the content?

**Comment by meshipeer** [comment]
the word 'write' maybe we need a different header?

**Comment by orius123** [comment]
ok. any suggestions?
blog is up!

**Comment by SamMarkowitz** [comment]
In the blog header there is overlapping text:

image

**Comment by SamMarkowitz** [comment]
There should be an easy way to get from the blog to the site.

**Pull request merged**
