### PR TITLE
fix CloudSlang cli  download link

### PR DESCRIPTION
**Pull request by meirwah**
it points to CLI iinstead of CLi-with-content

### CODE REVIEW

**Comment by meirwah** [comment]
whati do not understand, is how old website is already affected by this issue?? how old website points to 0.8 version today???

**Comment by meirwah** [comment]
@orius123 @gal1419 ?

**Comment by gal1419** [comment]
I'm getting the old file when downloading from the old website

**Comment by meirwah** [comment]
ok, so I'm merging this...

**Comment by meirwah** [comment]
can you upload this to the staging website? so we can verify it?

**Comment by gal1419** [comment]
Yes, but the link should be updated in the controller as well. 
I'll update first

**Pull request merged**
